function [trans_prob_o_all,v_new_resh_o_all,dist_o_all,measure_vec_o,p_e_o_vec,input_all_o,...
    trans_prob_n_all,v_new_resh_n_all,dist_n_all,measure_vec_n,p_E_vec,cap_old,cap_new,...
    age_g,a_grid_old,a_prob_old,a_grid_n_all,a_prob_n_all,entry_n_path,adopt_n_path,tax_revenue_path,entry_o_path] = ...
    MIT_transition_green(a_grow,alpha,beta,c_of_a,c_a_new_vec,a_grid_old,a_prob_old,...
    mu_new_vec,sigma_new_vec,a_num_g,age_num,max_iter,v_tol,fco_o,fco_n,e_p,d_0,...
    c_of_e,c_e_new_vec,dem_tol,init_dist_n,init_dist_o,final_val_o,final_val_n,...
    init_p_E,final_p_E,trans_t,final_dist_n,final_dist_o,e0_o,e_o_eps,...
    fin_p_e_o,init_p_e_o,rho,age_reduc,exit_n_final,exit_o_final,exo_exit,...
    init_input_o,penalty_o,penalty_p,d0_gr,rho_p_o,sigma_p_o,solar_cap_mean,solar_price_corr,fossil_tax_vec,...
    fossil_path,P_E_grid_norm,checkpoint_name,static_solver_workers)
% Fossil-green MIT. Trailing inputs are optional for legacy callers.

if nargin<47 || isempty(fossil_tax_vec)
    fossil_tax_vec = zeros(1,trans_t);
end
if nargin<48 || isempty(fossil_path)
    fossil_path = struct;
end
if nargin<49 || isempty(P_E_grid_norm)
    P_E_grid_norm = P_E_grid(50,1);
end
if nargin<50
    checkpoint_name = "";
end
if nargin<51
    static_solver_workers = [];
end
[trans_prob_o_all,v_new_resh_o_all,dist_o_all,measure_vec_o,p_e_o_vec,input_all_o,...
    trans_prob_n_all,v_new_resh_n_all,dist_n_all,measure_vec_n,p_E_vec,cap_old,cap_new,...
    age_g,a_grid_old,a_prob_old,a_grid_n_all,a_prob_n_all,entry_n_path,adopt_n_path,tax_revenue_path,entry_o_path] = ...
    MIT_transition_green_fast(a_grow,alpha,beta,c_of_a,c_a_new_vec,a_grid_old,a_prob_old,...
    mu_new_vec,sigma_new_vec,a_num_g,age_num,max_iter,v_tol,fco_o,fco_n,e_p,d_0,...
    c_of_e,c_e_new_vec,dem_tol,init_dist_n,init_dist_o,final_val_o,final_val_n,...
    init_p_E,final_p_E,trans_t,final_dist_n,final_dist_o,e0_o,e_o_eps,...
    fin_p_e_o,init_p_e_o,rho,age_reduc,exit_n_final,exit_o_final,exo_exit,...
    init_input_o,penalty_o,penalty_p,d0_gr,rho_p_o,sigma_p_o,solar_cap_mean,...
    solar_price_corr,fossil_tax_vec,fossil_path,P_E_grid_norm,checkpoint_name,...
    static_solver_workers);
end
