function [trans_prob_o,v_new_o,v_new_resh_o,dist_o,trans_matrix_n,p_e_n,cap_contemp_new,eff_n_final,...
    trans_prob_n,v_new_n,v_new_resh_n,dist_n,trans_matrix_o,p_e_o,cap_contemp_old,eff_o_final,...
    age_g,a_grid_old,a_prob_old,a_grid_new,a_prob_new,pi_contemp_new,p_E,m_of_firms_new,m_of_firms_old,exit_n,exit_o] = ...
    Two_tech_ss_AC3(a_grow,alpha,~,beta,c_of_a,c_a_new,mu_old,sigma_old,mu_new,sigma_new,a_num_g,age_num,max_iter,...
    v_tol,dist_tol,fco_o,fco_n,e_p,d_0,c_of_e,c_e_new,dem_tol,tech_dist,...
    e0_o,e_o_eps,rho_p_o,sigma_p_o,rho,age_reduc,exo_exit,solar_cap_mean,solar_price_corr,...
    P_E_grid_norm,fossil_terminal)
% Fossil-green steady state. Optional explicit fossil terminal states and a
% shared electricity-price quadrature grid preserve continuity with the MIT.

if nargin<33 || isempty(P_E_grid_norm)
    P_E_grid_norm = P_E_grid(50,1);
end
if nargin<34 || isempty(fossil_terminal)
    fossil_terminal = struct;
end
[trans_prob_o,v_new_o,v_new_resh_o,dist_o,trans_matrix_n,p_e_n,cap_contemp_new,eff_n_final,...
    trans_prob_n,v_new_n,v_new_resh_n,dist_n,trans_matrix_o,p_e_o,cap_contemp_old,eff_o_final,...
    age_g,a_grid_old,a_prob_old,a_grid_new,a_prob_new,pi_contemp_new,p_E,m_of_firms_new,m_of_firms_old,exit_n,exit_o] = ...
    Two_tech_ss_AC3_fast(a_grow,alpha,beta,c_of_a,c_a_new,mu_old,sigma_old,mu_new,sigma_new,a_num_g,age_num,max_iter,...
    v_tol,dist_tol,fco_o,fco_n,e_p,d_0,c_of_e,c_e_new,dem_tol,tech_dist,e0_o,e_o_eps,...
    rho_p_o,sigma_p_o,rho,age_reduc,exo_exit,solar_cap_mean,solar_price_corr,P_E_grid_norm,fossil_terminal);
end
